type Character {
  id: ID!
  name: String!
  weight: Int!
  pic_url: String!
  big_url: String!
  zero_rank: String!
  esam_rank: String!
  leffen_rank: String!
}

extend type Query {
  characters: [Character!]!
  character(id: ID!): Character!
}

extend type Mutation {
  # newProduct(input: NewProductInput!): Product!
  # updateProduct(id: ID!, input: UpdateProductInput!): Product!
  # removeProduct(id: ID!): Product!
}